### PR TITLE
Setting and removing metadata 

### PR DESCRIPTION
**Pull request by alexeykosh**
Hi! 

I just added one new method to delete metadata values (remove_meta) and changed the set_meta method for it to rise exceptions when the key is not empty, instead of not allowing users to change text data.

### CODE REVIEW

**Comment by matgrioni** [comment]
Hi Alexey!

Thanks for the PR. The functionality on `remove_meta` looks fine to me and is definitely needed. Could you expand on the comments to include the `Args` section. I know it is self explanatory, but since the documentation is auto-generated from these, I'd like for each method public to have something.

However, for the `set_meta` I am not sure I understand the change. The change in the PR means that no metadata can be directly changed; only added, removed, or retrieved. The Sentence.TEXT_KEY guard is only there explicitly to avoid changing of the underlying text, since I did not want users to change the token text and then expect the comments to also update. It is not nice, and it is on the backlog to improve, but I preferred data consistency to loose invariants and guarantees.

One more thing that I must add to the README also, is if you could open the PR against the `dev` branch as this is where the changes for the next release stage before I merge into `master`.

**Comment by alexeykosh** [comment]
> Could you expand on the comments to include the Args section.

Of course, I'll do that! 

> However, for the set_meta I am not sure I understand the change. The change in the PR means that no metadata can be directly changed; only added, removed, or retrieved. The Sentence.TEXT_KEY guard is only there explicitly to avoid changing the underlying text since I did not want users to change the token text and then expect the comments to also update. It is not nice, and it is on the backlog to improve, but I preferred data consistency to loose invariants and guarantees.

I did it because it did not allow me to change my 'text' metadata. So I rewrote to able to change it on the go. And what do you mean by 'expect the comments to also update'?

**Comment by matgrioni** [comment]
The `text` comment is unique in that its value has direct correspondance with the value in the tokens. If the token were to change, then the `text` should also change from the point of view of the UD format. However, this correspondance was difficult to guarantee in the library because Tokens are just children of Sentence, and so having this information synchronized is not straightforward as-is, and so any changes to one view of the data would require changes to the other but I felt this would be difficult for users

My safe approach was to simply not allow any changes to either and to leave pyconll for only changing annotations and not the text.

So in the context of what the change is intended to solve, there is no need for any check. But since my above concern has not changed, I would prefer no change to this method, until I can think about the problem more. In the meantime, you should be able to simply access `sentence._meta['text']` as a workaround.

Unfortunately there are a few comments in UD, like `newpar`, `newdoc`, and `text` that require  some understanding between objects, but I have not been able to come up with a solution to do so.


May I ask how exactly you are changing the text field? Is this to add a new `text` comment or changing an existing one?

**Comment by matgrioni** [comment]
Thanks for contribution Alexey. I assumed the last changes were fine, and have merged them, and will close this PR now.

**Pull request closed without merging**
